### PR TITLE
Added entries for v.2.2.2 to v. 4.0

### PR DESCRIPTION
**Pull request by vanina-iv**
Backdated changelog with items for versions v.2.2.2 to v. 4.0, more info here: https://github.com/AdExNetwork/adex-platform/issues/342

### CODE REVIEW

**Comment by TRtomasz** [comment]
Please wait with this i have much more :)
Here is all i got. I tried to pick all changes that are somehow meaningful to the users. Perhaps some are missing because commits messages are sometimes like this. 
image
 So under this link you can check everything i gathered i wonder maybe we should combine all past changes into two big groups(To do not have an entry for every version) If you agree let me know i will adjust it
1. 4.0.1 to 4.2.8 
2. 4.10.0 to 4.10.25
https://demo.codimd.org/s/HkRTMubE8#41025

**Comment by rori4** [comment]
I would be easier if you watch the pull requests here on GitHub. For every pull request there is a summary of what is added, fixed or closed with that pull request. The tough part would be to find which PR is added to which release.

**Comment by TRtomasz** [comment]
@rori4  i think i went through all commits so when there were pull requests with listed issues it is added in the change log (very helpful)

**Comment by ivopaunov** [comment]
I'll check this next week.

**Comment by TRtomasz** [comment]
@IvoPaunov  small reminder about changelog

**Comment by ivopaunov** [comment]
It does not look full but I'm merging it anyway

**Pull request merged**
